# Generated by Django 4.2 on 2025-10-01 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Equipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("modelo", models.CharField(blank=True, max_length=100)),
                ("fabricante", models.CharField(blank=True, max_length=255)),
                ("descricao", models.TextField(blank=True)),
                ("caracteristicas", models.JSONField(blank=True, default=list)),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="equipamentos/videos/"
                    ),
                ),
                ("manual_url", models.URLField(blank=True, null=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipamentos",
                        to="equipamentos.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EquipamentoImagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="equipamentos/imagens/")),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="equipamentos.equipamento",
                    ),
                ),
            ],
        ),
    ]
