# Generated by Django 4.2 on 2025-10-01 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("equipamentos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipamento",
            name="caracteristicas",
        ),
        migrations.CreateModel(
            name="EquipamentoCaracteristica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caracteristicas",
                        to="equipamentos.equipamento",
                    ),
                ),
            ],
        ),
    ]
