# Generated by Django 4.2 on 2025-10-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipamentos", "0002_remove_equipamento_caracteristicas_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipamento",
            name="video",
        ),
        migrations.AlterField(
            model_name="equipamentoimagem",
            name="imagem",
            field=models.URLField(),
        ),
    ]
