# Generated by Django 4.2 on 2025-10-31 13:57

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):
    dependencies = [
        ("equipamentos", "0003_remove_equipamento_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="explicacao",
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
