# Generated by Django 4.2 on 2025-10-31 14:08

from django.db import migrations

def copy_descricao_to_explicacao(apps, schema_editor):
    Categoria = apps.get_model('equipamentos', 'Categoria')
    
    for categoria in Categoria.objects.all():
        categoria.explicacao = categoria.descricao
        categoria.save()
    
    print(f"Copied {Categoria.objects.count()} Categoria records")

def reverse_copy(apps, schema_editor):
    Categoria = apps.get_model('equipamentos', 'Categoria')
    
    for categoria in Categoria.objects.all():
        categoria.descricao = categoria.explicacao
        categoria.save()


class Migration(migrations.Migration):
    dependencies = [
        ("equipamentos", "0004_categoria_explicacao"),
    ]

    operations = [
        migrations.RunPython(copy_descricao_to_explicacao, reverse_copy),
    ]
