# Generated by Django 4.2 on 2025-10-31 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("equipamentos", "0005_copy_categoria_descricao_to_explicacao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoria",
            name="descricao",
        ),
    ]
