# Generated by Django 4.2 on 2024-01-24 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Procedimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=250)),
                ("descricao", models.CharField(blank=True, max_length=250, null=True)),
                ("objetivo", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "responsabilidade",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("definicoes", models.TextField(blank=True, null=True)),
                (
                    "documentos_de_referencia",
                    models.ManyToManyField(to="documentos.documentoexterno"),
                ),
                (
                    "procedimentos_relacionados",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="procedimentos.procedimento",
                        verbose_name="Documentos relacionados",
                    ),
                ),
            ],
        ),
    ]
