# Generated by Django 4.2 on 2024-03-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0004_alter_documento_analise_critica"),
        ("procedimentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedimento",
            name="documentos_de_referencia",
            field=models.ManyToManyField(
                blank=True, null=True, to="documentos.documentoexterno"
            ),
        ),
    ]
