# Generated by Django 4.2 on 2024-03-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0004_alter_documento_analise_critica"),
        ("procedimentos", "0002_alter_procedimento_documentos_de_referencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedimento",
            name="documentos_de_referencia",
            field=models.ManyToManyField(blank=True, to="documentos.documentoexterno"),
        ),
    ]
