# Generated by Django 4.2 on 2024-01-24 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aprovacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_aprovacao", models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificador",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("titulo", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("V", "Vigente"),
                            ("O", "Obsoleto"),
                            ("C", "Cancelado"),
                        ],
                        default="V",
                        max_length=1,
                    ),
                ),
                ("data_revisao", models.DateField(blank=True, null=True)),
                ("data_validade", models.DateField(blank=True, null=True)),
                ("analise_critica", models.IntegerField(blank=True, null=True)),
                ("unidade", models.CharField(blank=True, max_length=50, null=True)),
                ("elaborador", models.CharField(blank=True, max_length=250, null=True)),
                ("arquivo", models.FileField(upload_to="documentos/")),
                ("frequencia", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoExterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=100, null=True)),
                ("titulo", models.CharField(blank=True, max_length=250, null=True)),
                ("link_de_acesso", models.URLField(blank=True, null=True)),
                ("data_da_atualizacao", models.DateField(blank=True, null=True)),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("V", "Vigente"),
                            ("O", "Obsoleto"),
                            ("C", "Cancelado"),
                        ],
                        default="V",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Revisao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_revisao", models.DateField(auto_now_add=True)),
                ("alteracao", models.TextField(blank=True, null=True)),
                (
                    "documento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisoes",
                        to="documentos.documento",
                    ),
                ),
                (
                    "revisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
