# Generated by Django 4.2 on 2024-01-24 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("procedimentos", "0001_initial"),
        ("documentos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="codigo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="procedimentos.procedimento",
            ),
        ),
        migrations.AddField(
            model_name="aprovacao",
            name="aprovador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aprovacoes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aprovacao",
            name="revisao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aprovacoes",
                to="documentos.revisao",
            ),
        ),
    ]
