# Generated by Django 4.2 on 2024-01-24 23:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documento",
            name="unidade",
        ),
    ]
