# Generated by Django 4.2 on 2024-02-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0003_remove_documento_unidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="analise_critica",
            field=models.IntegerField(blank=True, help_text="Em dias", null=True),
        ),
    ]
