# Generated by Django 4.2 on 2024-06-07 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documentos", "0004_alter_documento_analise_critica"),
    ]

    operations = [
        migrations.AddField(
            model_name="revisao",
            name="aprovadores",
            field=models.ManyToManyField(
                related_name="revisoes_autorizadas", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="analise_critica",
            field=models.IntegerField(blank=True, help_text="Em meses", null=True),
        ),
        migrations.AlterField(
            model_name="documento",
            name="frequencia",
            field=models.IntegerField(blank=True, help_text="Em anos", null=True),
        ),
    ]
