# Generated by Django 4.2 on 2024-06-11 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "documentos",
            "0005_revisao_aprovadores_alter_documento_analise_critica_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="criador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="criador_documento",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
