# Generated by Django 4.2 on 2024-06-11 01:14

from django.db import migrations


def convert(apps, schema_editor):
    documents_model = apps.get_model("documentos", "Documento")
    User = apps.get_model("auth", "User")
    for document in documents_model.objects.all():
        elaborador = document.elaborador
        user = User.objects.filter(username__contains=elaborador).first()
        if user:
            document.criador = user
            document.save()


def revert(apps, schema_editor):
    documents_model = apps.get_model("documentos", "Documento")
    User = apps.get_model("auth", "User")
    for document in documents_model.objects.all():
        criador = document.criador.username
        if criador:
            document.elaborador = criador
            document.save()


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0006_documento_criador"),
    ]

    operations = [migrations.RunPython(convert, migrations.RunPython.noop)]
