# Generated by Django 4.2 on 2024-06-11 01:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0007_auto_20240610_2214"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documento",
            name="elaborador",
        ),
    ]
