# Generated by Django 4.2 on 2024-07-08 02:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documentos", "0008_remove_documento_elaborador"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="aprovacao",
            unique_together={("aprovador", "revisao")},
        ),
    ]
