# Generated by Django 4.2 on 2024-07-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0009_alter_aprovacao_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="revisao",
            options={"ordering": ["-data_revisao"]},
        ),
        migrations.AlterField(
            model_name="documento",
            name="analise_critica",
            field=models.IntegerField(blank=True, help_text="Em dias", null=True),
        ),
    ]
