# Generated by Django 4.2 on 2024-07-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0010_alter_revisao_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="arquivo_PDF",
            field=models.FileField(blank=True, null=True, upload_to="documentosPDF/"),
        ),
    ]
