# Generated by Django 4.2 on 2024-08-01 04:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0011_documento_arquivo_pdf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documento",
            name="arquivo_PDF",
        ),
    ]
