# Generated by Django 4.2 on 2024-08-08 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0012_remove_documento_arquivo_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revisao",
            name="documento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisoes",
                to="documentos.documento",
            ),
        ),
    ]
