# Generated by Django 4.2 on 2024-08-08 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0013_alter_revisao_documento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aprovacao",
            name="revisao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aprovacoes",
                to="documentos.revisao",
            ),
        ),
    ]
