# Generated by Django 4.2 on 2024-09-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0014_alter_aprovacao_revisao"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="vencido",
            field=models.BooleanField(default=False),
        ),
    ]
