# Generated by Django 4.2 on 2025-03-26 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0015_documento_vencido"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documento",
            name="data_revisao",
        ),
    ]
