# Generated by Django 4.2 on 2025-03-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0016_remove_documento_data_revisao"),
    ]

    operations = [
        migrations.AddField(
            model_name="revisao",
            name="tipo",
            field=models.CharField(
                choices=[("revalidar", "Revalidar"), ("revisar", "Revisar")],
                default="revisar",
                max_length=9,
                verbose_name="tipo",
            ),
        ),
    ]
