# Generated by Django 4.2 on 2025-03-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0017_revisao_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="ultima_notificacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
