# Generated by Django 4.2 on 2025-04-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0018_documento_ultima_notificacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="revisao",
            name="ultima_notificacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
