# Generated by Django 4.2 on 2025-09-09 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0008_remove_cliente_cpf_remove_cliente_nome_and_more"),
        ("documentos", "0019_revisao_ultima_notificacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentos",
                to="clientes.cliente",
            ),
        ),
    ]
