# Generated by Django 4.2 on 2026-02-25 17:18

from django.db import migrations, models, connection
import django.db.models.deletion


def apply_migration_0002_idempotent(apps, schema_editor):
    """
    Apply all operations from migration 0002 in an idempotent way.
    Checks if columns/tables exist before adding them.
    """
    db_alias = schema_editor.connection.alias
    
    with connection.cursor() as cursor:
        # Get database name
        cursor.execute("SELECT DATABASE()")
        db_name = cursor.fetchone()[0]
        
        # Check existing columns in ordem_servico_ordemservico
        cursor.execute("""
            SELECT COLUMN_NAME 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = %s
            AND TABLE_NAME = 'ordem_servico_ordemservico'
        """, [db_name])
        existing_columns = {row[0] for row in cursor.fetchall()}
        
        # Check if InstrumentoOS table exists
        cursor.execute("""
            SELECT TABLE_NAME 
            FROM information_schema.TABLES 
            WHERE TABLE_SCHEMA = %s
            AND TABLE_NAME = 'ordem_servico_instrumentoos'
        """, [db_name])
        instrumentos_table_exists = cursor.fetchone() is not None
        
        # 1. Add fields to OrdemServico if they don't exist
        fields_to_add = {
            'data_calibracao_instrumentos': {
                'type': 'DATE',
                'nullable': True,
                'default': None,
            },
            'data_liberacao_calibracao': {
                'type': 'DATE',
                'nullable': True,
                'default': None,
            },
            'data_liberacao_instrumentos': {
                'type': 'DATE',
                'nullable': True,
                'default': None,
            },
            'data_recebimento_instrumentos': {
                'type': 'DATE',
                'nullable': True,
                'default': None,
            },
            'status': {
                'type': 'VARCHAR(2)',
                'nullable': False,
                'default': "'AR'",
            },
            'tipo_os': {
                'type': 'VARCHAR(3)',
                'nullable': True,
                'default': None,
            },
        }
        
        for field_name, field_def in fields_to_add.items():
            if field_name not in existing_columns:
                null_clause = 'NULL' if field_def['nullable'] else 'NOT NULL'
                default_clause = f"DEFAULT {field_def['default']}" if field_def['default'] else ''
                sql = f"""
                    ALTER TABLE ordem_servico_ordemservico 
                    ADD COLUMN {field_name} {field_def['type']} {null_clause} {default_clause}
                """
                cursor.execute(sql)
                print(f"✓ Added column: {field_name}")
            else:
                print(f"⊘ Column {field_name} already exists, skipping")
        
        # 2. Create InstrumentoOS table if it doesn't exist
        if not instrumentos_table_exists:
            # Create the table with all fields
            cursor.execute("""
                CREATE TABLE ordem_servico_instrumentoos (
                    id BIGINT AUTO_INCREMENT PRIMARY KEY,
                    item INTEGER NOT NULL,
                    observacao LONGTEXT NULL,
                    local VARCHAR(1) NULL,
                    marca_reparo BOOLEAN NULL DEFAULT FALSE,
                    marca_selagem_nova BOOLEAN NULL DEFAULT FALSE,
                    marca_selagem_retirada VARCHAR(255) NULL,
                    servico_executado LONGTEXT NULL,
                    descricao_anomalia LONGTEXT NULL,
                    quantidade INTEGER NULL,
                    instrumento_id BIGINT NOT NULL,
                    ordem_servico_id BIGINT NOT NULL,
                    CONSTRAINT ordem_servico_instrumentoos_instrumento_id_fk 
                        FOREIGN KEY (instrumento_id) 
                        REFERENCES instrumentos_instrumentodocliente(id) 
                        ON DELETE CASCADE,
                    CONSTRAINT ordem_servico_instrumentoos_ordem_servico_id_fk 
                        FOREIGN KEY (ordem_servico_id) 
                        REFERENCES ordem_servico_ordemservico(id) 
                        ON DELETE CASCADE,
                    UNIQUE KEY ordem_servico_instrumentoos_unique (ordem_servico_id, item)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
            """)
            print("✓ Created table: ordem_servico_instrumentoos")
        else:
            print("⊘ Table ordem_servico_instrumentoos already exists, skipping")
        
        # 3. Check if the ManyToManyField through relationship needs to be updated
        # This is handled by Django's state, but we need to ensure the through table exists
        # (which we already checked above)
        
        # 4. Check if unique constraint exists
        cursor.execute("""
            SELECT CONSTRAINT_NAME 
            FROM information_schema.TABLE_CONSTRAINTS 
            WHERE TABLE_SCHEMA = %s
            AND TABLE_NAME = 'ordem_servico_instrumentoos'
            AND CONSTRAINT_TYPE = 'UNIQUE'
            AND CONSTRAINT_NAME = 'ordem_servico_instrumentoos_unique'
        """, [db_name])
        unique_constraint_exists = cursor.fetchone() is not None
        
        if instrumentos_table_exists and not unique_constraint_exists:
            try:
                cursor.execute("""
                    ALTER TABLE ordem_servico_instrumentoos 
                    ADD CONSTRAINT ordem_servico_instrumentoos_unique 
                    UNIQUE (ordem_servico_id, item)
                """)
                print("✓ Added unique constraint")
            except Exception as e:
                print(f"⊘ Could not add unique constraint (may already exist): {e}")


def reverse_migration_0002(apps, schema_editor):
    """Reverse operation - remove what was added"""
    with connection.cursor() as cursor:
        # Remove unique constraint
        try:
            cursor.execute("""
                ALTER TABLE ordem_servico_instrumentoos 
                DROP INDEX ordem_servico_instrumentoos_unique
            """)
        except Exception:
            pass
        
        # Drop InstrumentoOS table
        try:
            cursor.execute("DROP TABLE IF EXISTS ordem_servico_instrumentoos")
        except Exception:
            pass
        
        # Remove columns
        columns_to_remove = [
            'data_calibracao_instrumentos',
            'data_liberacao_calibracao',
            'data_liberacao_instrumentos',
            'data_recebimento_instrumentos',
            'status',
            'tipo_os',
        ]
        for column in columns_to_remove:
            try:
                cursor.execute(f"""
                    ALTER TABLE ordem_servico_ordemservico 
                    DROP COLUMN {column}
                """)
            except Exception:
                pass


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0059_instrumentodocliente_numero_certificado"),
        ("ordem_servico", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Executa a lógica idempotente no banco (checa se coluna/tabela existe antes)
                migrations.RunPython(
                    apply_migration_0002_idempotent,
                    reverse_migration_0002,
                ),
            ],
            state_operations=[
                # Atualiza apenas o estado do Django (sem gerar SQL extra),
                # assumindo que o banco já foi ajustado pelo RunPython acima.
                migrations.AddField(
                    model_name="ordemservico",
                    name="data_calibracao_instrumentos",
                    field=models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de calibração dos instrumentos",
                    ),
                ),
                migrations.AddField(
                    model_name="ordemservico",
                    name="data_liberacao_calibracao",
                    field=models.DateField(
                        blank=True, null=True, verbose_name="Data liberação da calibração"
                    ),
                ),
                migrations.AddField(
                    model_name="ordemservico",
                    name="data_liberacao_instrumentos",
                    field=models.DateField(
                        blank=True, null=True, verbose_name="Data liberação instrumentos"
                    ),
                ),
                migrations.AddField(
                    model_name="ordemservico",
                    name="data_recebimento_instrumentos",
                    field=models.DateField(
                        blank=True, null=True, verbose_name="Data recebimento dos instrumentos"
                    ),
                ),
                migrations.AddField(
                    model_name="ordemservico",
                    name="status",
                    field=models.CharField(
                        choices=[
                            ("AR", "A realizar"),
                            ("EA", "Em andamento"),
                            ("RE", "Realizado"),
                            ("CA", "Cancelado"),
                        ],
                        default="AR",
                        max_length=2,
                        verbose_name="Status",
                    ),
                ),
                migrations.AddField(
                    model_name="ordemservico",
                    name="tipo_os",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("CAL", "OS Calibração"),
                            ("BAL", "OS Balanças"),
                            ("MAN", "OS Manutenção"),
                            ("EXT", "OS Serviços Externos"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="Tipo de OS",
                    ),
                ),
                migrations.CreateModel(
                    name="InstrumentoOS",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("item", models.IntegerField(verbose_name="Item")),
                        (
                            "observacao",
                            models.TextField(blank=True, null=True, verbose_name="Observação"),
                        ),
                        (
                            "local",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("P", "Instalação permanente"),
                                    ("C", "Instalação cliente"),
                                    ("T", "Terceirizada"),
                                ],
                                max_length=1,
                                null=True,
                                verbose_name="Local",
                            ),
                        ),
                        (
                            "marca_reparo",
                            models.BooleanField(
                                blank=True,
                                default=False,
                                null=True,
                                verbose_name="Marca de reparo",
                            ),
                        ),
                        (
                            "marca_selagem_nova",
                            models.BooleanField(
                                blank=True,
                                default=False,
                                null=True,
                                verbose_name="Marca de selagem nova",
                            ),
                        ),
                        (
                            "marca_selagem_retirada",
                            models.CharField(
                                blank=True,
                                max_length=255,
                                null=True,
                                verbose_name="Marca de selagem retirada",
                            ),
                        ),
                        (
                            "servico_executado",
                            models.TextField(
                                blank=True, null=True, verbose_name="Serviço executado"
                            ),
                        ),
                        (
                            "descricao_anomalia",
                            models.TextField(
                                blank=True, null=True, verbose_name="Descrição anomalia"
                            ),
                        ),
                        (
                            "quantidade",
                            models.IntegerField(
                                blank=True, null=True, verbose_name="Quantidade"
                            ),
                        ),
                        (
                            "instrumento",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="ordens_servico_os",
                                to="instrumentos.instrumentodocliente",
                                verbose_name="Instrumento",
                            ),
                        ),
                        (
                            "ordem_servico",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="instrumentos_os",
                                to="ordem_servico.ordemservico",
                                verbose_name="Ordem de Serviço",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Instrumento OS",
                        "verbose_name_plural": "Instrumentos OS",
                        "ordering": ["item"],
                        "unique_together": {("ordem_servico", "item")},
                    },
                ),
                migrations.AlterField(
                    model_name="ordemservico",
                    name="instrumentos",
                    field=models.ManyToManyField(
                        related_name="ordens_servico",
                        through="ordem_servico.InstrumentoOS",
                        to="instrumentos.instrumentodocliente",
                        verbose_name="Instrumentos",
                    ),
                ),
            ],
        ),
    ]