# Generated by Django 4.2 on 2026-03-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ordem_servico", "0002_ordemservico_data_calibracao_instrumentos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemservico",
            name="os_recebimento_dos_instruementos",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="OS de recebimento dos instrumentos (Manutenção)",
            ),
        ),
    ]
