# Generated by Django 4.2 on 2026-05-13 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("propostas", "0025_backfill_propostainstrumento_preco"),
        ("ordem_servico", "0003_ordemservico_os_recebimento_dos_instruementos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemservico",
            name="proposta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordens_servico",
                to="propostas.proposta",
                verbose_name="Proposta",
            ),
        ),
    ]
