# Generated by Codex on 2026-05-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
        ("ordem_servico", "0004_alter_ordemservico_proposta"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemservico",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordens_servico",
                to="clientes.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="tipo_os",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CAL", "OS Calibração"),
                    ("BAL", "OS Balanças"),
                    ("MAN", "OS Manutenção"),
                    ("EXT", "OS Serviços Externos"),
                    ("TV", "Visita Técnica"),
                ],
                max_length=3,
                null=True,
                verbose_name="Tipo de OS",
            ),
        ),
    ]
