# Generated by Django 4.2 on 2023-11-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="filial",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="nome_fantasia",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Nome Fantasia"
            ),
        ),
    ]
