# Generated by Django 4.2 on 2024-09-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0002_empresa_filial_empresa_nome_fantasia"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="instrumentos_cadastrados",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cliente",
            name="instrumentos_em_dia",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cliente",
            name="instrumentos_vencidos",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cliente",
            name="propostas_aguardando_aprovacao",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
