# Generated by Django 4.2 on 2025-09-02 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clientes", "0003_cliente_instrumentos_cadastrados_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="usuarios",
            field=models.ManyToManyField(
                blank=True, related_name="clientes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
