# Generated by Django 4.2 on 2025-09-02 17:43

from django.db import migrations


def copiar_usuario_para_usuarios(apps, schema_editor):
    Cliente = apps.get_model("clientes", "Cliente")
    for cliente in Cliente.objects.all():
        if cliente.usuario:
            cliente.usuarios.add(cliente.usuario)


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0004_cliente_usuarios"),
    ]

    operations = [
        migrations.RunPython(copiar_usuario_para_usuarios),
    ]
