# Generated by Django 4.2 on 2025-09-02 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0005_auto_20250902_1443"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="usuario",
        ),
    ]
