# Generated by Django 4.2 on 2025-09-03 14:12

from django.db import migrations


def criar_grupos(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    modelos = {
        "clientes": ["cliente"],
        "documentos": ["documento", "documentoexterno", "revisao", "aprovacao"],
        "instrumentos": [
            "instrumentodocliente", "calibracao",
            "instrumento", "tipoinstrumento", "setor"
        ],
        "procedimentos": ["procedimento"],
        "propostas": ["proposta"],
    }

    grupos = {
        "gerente": ["add", "change", "delete", "view"],
        "registrador": ["add", "view"],
        "observador": ["view"],
    }

    for grupo_nome, acoes in grupos.items():
        grupo, _ = Group.objects.get_or_create(name=grupo_nome)

        for app_label, models in modelos.items():
            for model in models:
                for acao in acoes:
                    codename = f"{acao}_{model}"
                    try:
                        perm = Permission.objects.get(
                            codename=codename,
                            content_type=ContentType.objects.get(app_label=app_label, model=model)
                        )
                        grupo.permissions.add(perm)
                    except (ContentType.DoesNotExist, Permission.DoesNotExist):
                        print(f"[WARN] Permissão {codename} para {app_label}.{model} não encontrada")


def remover_grupos(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for g in ["gerente", "registrador", "observador"]:
        Group.objects.filter(name=g).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0006_remove_cliente_usuario"),
    ]

    operations = [
        migrations.RunPython(criar_grupos, remover_grupos),
    ]

