# Generated by Django 4.2 on 2025-09-04 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0007_criar_grupos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="cpf",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="nome",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="telefone",
        ),
    ]
