# Generated by Django 4.2 on 2025-09-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0009_convite"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="criterio_frequencia_padrao",
            field=models.CharField(
                choices=[("C", "Tempo de calendário"), ("S", "Tempo de serviço")],
                default="C",
                max_length=1,
                verbose_name="Critério de frequência padrão",
            ),
        ),
    ]
