# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0012_passwordreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="convite",
            name="token",
            field=models.TextField(blank=True, default=""),
        ),
    ]