# Generated by Django 4.2 on 2026-05-12 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0013_convite_cliente_nullable"),
        ("clientes", "0013_convite_token"),
    ]

    operations = []
