# Generated by Django 4.2 on 2026-05-19 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clientes", "0014_merge_20260512_1613"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convite",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
