# Generated by Django 4.2 on 2023-11-14 13:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("instrumentos", "0001_initial"),
        ("enderecos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "informacoes_adicionais",
                    models.TextField(
                        blank=True, null=True, verbose_name="Informações adicionais"
                    ),
                ),
                (
                    "local",
                    models.CharField(
                        choices=[("L", "Laboratório"), ("C", "Cliente")],
                        default="L",
                        max_length=1,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("prazo_de_entrega", models.DateField(blank=True, null=True)),
                (
                    "condicao_de_pagamento",
                    models.CharField(
                        choices=[
                            ("CD", "Cartão débito"),
                            ("CC", "Cartão crédito"),
                            ("P", "Pix"),
                            ("D", "Dinheiro"),
                        ],
                        default="D",
                        max_length=2,
                        verbose_name="Condição de pagamento",
                    ),
                ),
                ("transporte", models.CharField(blank=True, max_length=512, null=True)),
                ("validade", models.DateField(blank=True, null=True)),
                ("anexo", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "aprovacao",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Aprovação"
                    ),
                ),
                (
                    "data_aprovacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data aprovação"
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data atualização"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "Em Análise"), ("F", "Finalizada")],
                        default="A",
                        max_length=2,
                    ),
                ),
                ("numero", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propostas",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "endereco_de_entrega",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="enderecos.endereco",
                        verbose_name="Endereço de entrega",
                    ),
                ),
                (
                    "instrumentos",
                    models.ManyToManyField(
                        related_name="propostas", to="instrumentos.instrumentodocliente"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PontoDeCalibracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                (
                    "proposta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pontos_de_calibracao",
                        to="propostas.proposta",
                    ),
                ),
            ],
        ),
    ]
