# Generated by Django 4.2 on 2024-03-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propostas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposta",
            name="condicao_de_pagamento",
            field=models.CharField(
                choices=[
                    ("CD", "Cartão débito"),
                    ("CC", "Cartão crédito"),
                    ("P", "Pix"),
                    ("D", "Dinheiro"),
                    ("B", "Boleto"),
                ],
                default="D",
                max_length=2,
                verbose_name="Condição de pagamento",
            ),
        ),
    ]
