# Generated by Django 4.2 on 2024-03-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propostas", "0002_alter_proposta_condicao_de_pagamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposta",
            name="numero",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="proposta",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=65),
        ),
    ]
