# Generated by Django 4.2 on 2024-05-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propostas", "0003_alter_proposta_numero_alter_proposta_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposta",
            name="prazo_de_pagamento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
