# Generated by Django 4.2 on 2024-05-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propostas", "0004_proposta_prazo_de_pagamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposta",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=65, null=True
            ),
        ),
    ]
