# Generated by Django 4.2 on 2024-06-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propostas", "0005_alter_proposta_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposta",
            name="numero",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
