# Generated by Django 4.2 on 2024-06-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propostas", "0006_alter_proposta_numero"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposta",
            name="local",
        ),
        migrations.RemoveField(
            model_name="proposta",
            name="prazo_de_entrega",
        ),
        migrations.AlterField(
            model_name="proposta",
            name="status",
            field=models.CharField(
                choices=[
                    ("E", "Elaboração"),
                    ("AA", "Aguardando aprovação"),
                    ("A", "Aprovada"),
                    ("R", "Reprovada"),
                ],
                default="E",
                max_length=2,
            ),
        ),
    ]
