# Generated by Django 4.2 on 2024-07-16 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("propostas", "0007_remove_proposta_local_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposta",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="propostas_responsaveis",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Funcionário Responsável",
            ),
        ),
    ]
