# Generated by Django 4.2 on 2024-08-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propostas", "0008_proposta_responsavel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposta",
            name="anexo",
            field=models.FileField(blank=True, null=True, upload_to="anexos/"),
        ),
    ]
