# Generated by Django 4.2 on 2024-08-15 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("propostas", "0009_alter_proposta_anexo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposta",
            name="aprovacao",
        ),
        migrations.DeleteModel(
            name="PontoDeCalibracao",
        ),
    ]
