# Generated by Django 4.2 on 2024-08-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propostas", "0010_remove_proposta_aprovacao_delete_pontodecalibracao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposta",
            name="data_aprovacao",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data aprovação"
            ),
        ),
    ]
