# Generated by Django 4.2 on 2024-08-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propostas", "0011_alter_proposta_data_aprovacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposta",
            name="dias_uteis",
            field=models.IntegerField(
                blank=True, help_text="Em dias", null=True, verbose_name="Dias úteis"
            ),
        ),
    ]
