# Generated by Django 4.2 on 2024-09-16 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("propostas", "0012_proposta_dias_uteis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposta",
            name="anexo",
        ),
        migrations.CreateModel(
            name="Revisao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf", models.FileField(blank=True, null=True, upload_to="revisoes/")),
                (
                    "proposta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisoes",
                        to="propostas.proposta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Anexo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anexo", models.FileField(blank=True, null=True, upload_to="anexos/")),
                (
                    "proposta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="propostas.proposta",
                    ),
                ),
            ],
        ),
    ]
