# Generated by Django 4.2 on 2024-09-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propostas", "0013_remove_proposta_anexo_revisao_anexo"),
    ]

    operations = [
        migrations.AddField(
            model_name="revisao",
            name="rev",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
