# Generated by Django 4.2 on 2024-09-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0017_instrumento_unidade_delete_unidade"),
        ("propostas", "0015_alter_proposta_instrumentos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposta",
            name="instrumentos",
            field=models.ManyToManyField(
                blank=True,
                related_name="propostas",
                to="instrumentos.instrumentodocliente",
            ),
        ),
    ]
