# Generated by Django 4.2 on 2025-06-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propostas", "0016_alter_proposta_instrumentos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposta",
            name="prazo_de_pagamento",
        ),
        migrations.AddField(
            model_name="proposta",
            name="desconto_percentual",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Desconto percentual aplicado sobre o valor total (ex: 10 para 10%)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="proposta",
            name="condicao_de_pagamento",
            field=models.CharField(max_length=50, verbose_name="Condição de pagamento"),
        ),
    ]
