# Generated by Django 4.2 on 2025-06-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propostas", "0017_remove_proposta_prazo_de_pagamento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposta",
            name="liberado_para_faturar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proposta",
            name="nf",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="proposta",
            name="nf_entrada",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="proposta",
            name="observacao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proposta",
            name="realizado",
            field=models.BooleanField(default=False),
        ),
    ]
