# Generated by Django 4.2 on 2025-06-17 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("propostas", "0018_proposta_liberado_para_faturar_proposta_nf_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposta",
            name="liberado_para_faturar",
        ),
        migrations.AddField(
            model_name="proposta",
            name="data_liberacao_faturamento",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data de Liberação para Faturamento"
            ),
        ),
        migrations.AddField(
            model_name="proposta",
            name="usuario_liberou_faturamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="liberacoes_faturamento",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário que Liberou para Faturamento",
            ),
        ),
        migrations.AlterField(
            model_name="proposta",
            name="condicao_de_pagamento",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Condição de pagamento",
            ),
        ),
    ]
