# Generated by Django 4.2 on 2025-06-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propostas", "0019_remove_proposta_liberado_para_faturar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposta",
            name="usuario_liberou_faturamento",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
