# Generated by Django 4.2 on 2025-08-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propostas", "0020_alter_proposta_usuario_liberou_faturamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposta",
            name="local",
            field=models.CharField(
                choices=[
                    ("P", "Instalação permanente"),
                    ("C", "Instalação cliente"),
                    ("T", "Terceirizada"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
