# Generated by Django 4.2 on 2026-02-06 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0059_instrumentodocliente_numero_certificado"),
        ("propostas", "0021_proposta_local"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropostaInstrumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_kind",
                    models.CharField(
                        choices=[
                            ("calibracao", "Calibração"),
                            ("manutencao", "Manutenção"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de serviço",
                    ),
                ),
                (
                    "local",
                    models.CharField(
                        choices=[
                            ("P", "Instalação permanente"),
                            ("C", "Instalação cliente"),
                            ("T", "Terceirizada"),
                        ],
                        max_length=1,
                        verbose_name="Local",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de atualização"
                    ),
                ),
                (
                    "instrumento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propostas_selecoes",
                        to="instrumentos.instrumentodocliente",
                        verbose_name="Instrumento",
                    ),
                ),
                (
                    "proposta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrumentos_selecoes",
                        to="propostas.proposta",
                        verbose_name="Proposta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seleção de Serviço do Instrumento",
                "verbose_name_plural": "Seleções de Serviço dos Instrumentos",
                "ordering": ["created_at"],
                "unique_together": {("proposta", "instrumento")},
            },
        ),
    ]
