# Generated by Django 4.2 on 2026-03-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("propostas", "0022_propostainstrumento"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposta",
            name="tipo_servico",
            field=models.CharField(
                blank=True,
                choices=[
                    ("acreditado", "Acreditado"),
                    ("nao_acreditado", "Não acreditado"),
                ],
                help_text="Classificação manual da proposta: acreditado ou não acreditado.",
                max_length=20,
                null=True,
                verbose_name="Tipo de serviço (proposta)",
            ),
        ),
    ]
