# Generated by Django 4.2 on 2025-06-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("empresa", models.CharField(blank=True, max_length=100)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="avaliacoes/"),
                ),
                ("comentario", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
