# Generated by Django 4.2 on 2025-06-12 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("conteudo", models.TextField()),
                (
                    "imagem_destaque",
                    models.ImageField(blank=True, null=True, upload_to="blog/posts/"),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "video_arquivo",
                    models.FileField(blank=True, null=True, upload_to="blog/videos/"),
                ),
                ("publicado_em", models.DateTimeField(auto_now_add=True)),
                ("visivel", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="blog.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImagemExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="blog/posts/extras/")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens_adicionais",
                        to="blog.post",
                    ),
                ),
            ],
        ),
    ]
