# Generated by Django 4.2 on 2025-09-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="destaque",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="resumo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
