# Generated by Django 4.2 on 2025-09-24 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_destaque_post_resumo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="video_url",
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos_url",
                        to="blog.post",
                    ),
                ),
            ],
        ),
    ]
