# Generated by Django 4.2 on 2025-09-25 19:25

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_remove_post_video_url_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="texto",
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
