# Generated by Django 4.2 on 2025-10-02 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_texto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="conteudo",
        ),
    ]
