# Generated by Django 4.2 on 2025-10-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_remove_post_conteudo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="video_arquivo",
        ),
        migrations.AddField(
            model_name="post",
            name="imagem_destaque_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="imagemextra",
            name="imagem",
            field=models.URLField(),
        ),
    ]
