# Generated by Django 4.2 on 2023-11-14 13:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapacidadeMedicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unidade", models.CharField(max_length=16)),
            ],
            options={
                "verbose_name": "Capacidade de medição",
                "verbose_name_plural": "Capacidades de medição",
            },
        ),
        migrations.CreateModel(
            name="Instrumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maximo",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Máximo"
                    ),
                ),
                (
                    "minimo",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Mínimo"
                    ),
                ),
                ("unidade", models.CharField(max_length=16)),
                (
                    "preco_calibracao_no_cliente",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Preço calibração no cliente",
                    ),
                ),
                (
                    "preco_calibracao_no_laboratorio",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Preço calibração no laboratório",
                    ),
                ),
                (
                    "tipo_de_servico",
                    models.CharField(
                        choices=[("A", "Acreditado"), ("NA", "Não acreditado")],
                        default="A",
                        max_length=2,
                        verbose_name="Tipo de serviço",
                    ),
                ),
                (
                    "capacidade_de_medicao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="instrumentos.capacidademedicao",
                        verbose_name="Capacidade de medição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrumento",
                "verbose_name_plural": "Instrumentos",
            },
        ),
        migrations.CreateModel(
            name="ProcedimentoRelacionado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("procedimento", models.CharField(max_length=512)),
            ],
            options={
                "verbose_name_plural": "Procedimentos Relacionados",
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=512)),
                ("cor", models.CharField(default="success", max_length=20)),
            ],
            options={
                "verbose_name_plural": "Status",
            },
        ),
        migrations.CreateModel(
            name="TipoInstrumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=512, verbose_name="Descrição"),
                ),
                ("modelo", models.CharField(max_length=512)),
                ("fabricante", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "resolucao",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        null=True,
                        verbose_name="Resolução",
                    ),
                ),
                (
                    "frequencia",
                    models.PositiveIntegerField(
                        blank=True,
                        default=30,
                        null=True,
                        verbose_name="Frequencia de calibração (em dias)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de instrumento",
                "verbose_name_plural": "Tipos de instrumento",
            },
        ),
        migrations.CreateModel(
            name="InstrumentoDoCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=512)),
                (
                    "numero_de_serie",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Número de série",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_proxima_checagem",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da próxima checagem"
                    ),
                ),
                (
                    "laboratorio",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "posicao",
                    models.CharField(
                        choices=[
                            ("U", "Em uso"),
                            ("E", "Em estoque"),
                            ("I", "Inativo"),
                            ("F", "Fora de uso"),
                        ],
                        default="I",
                        max_length=1,
                        verbose_name="Posição do instrumento",
                    ),
                ),
                (
                    "data_proxima_calibracao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da próxima calibração"
                    ),
                ),
                (
                    "data_ultima_calibracao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da última calibração"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrumentos",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "instrumento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrumentos",
                        to="instrumentos.instrumento",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="instrumentos.status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrumento do cliente",
                "verbose_name_plural": "Instrumentos dos clientes",
            },
        ),
        migrations.AddField(
            model_name="instrumento",
            name="procedimento_relacionado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="instrumentos.procedimentorelacionado",
            ),
        ),
        migrations.AddField(
            model_name="instrumento",
            name="tipo_de_instrumento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intrumento",
                to="instrumentos.tipoinstrumento",
                verbose_name="Tipo de instrumento",
            ),
        ),
        migrations.CreateModel(
            name="Calibracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordem_de_servico",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Ordem de serviço",
                    ),
                ),
                (
                    "local",
                    models.CharField(
                        max_length=512, null=True, verbose_name="Local da calibração"
                    ),
                ),
                (
                    "numero_do_certificado",
                    models.CharField(
                        max_length=512, verbose_name="Número do certificado"
                    ),
                ),
                (
                    "certificado",
                    models.FileField(blank=True, null=True, upload_to="certificados/"),
                ),
                (
                    "data",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Data da calibração",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "Aprovado"), ("R", "Reprovado")],
                        default="R",
                        help_text="Aprovação é definida por: |Maior erro| + |Incerteza| < Critério de aceitação",
                        max_length=1,
                    ),
                ),
                (
                    "maior_erro",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "incerteza",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "criterio_de_aceitacao",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Critério de aceitação",
                    ),
                ),
                (
                    "referencia_do_criterio",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Referência do critério de aceitação",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "instrumento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibracoes",
                        to="instrumentos.instrumentodocliente",
                        verbose_name="Instrumento calibrado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calibração",
                "verbose_name_plural": "Calibrações",
            },
        ),
    ]
