# Generated by Django 4.2 on 2024-01-24 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("procedimentos", "0001_initial"),
        ("instrumentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unidade", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="instrumento",
            name="unidade",
        ),
        migrations.RemoveField(
            model_name="instrumentodocliente",
            name="status",
        ),
        migrations.AlterField(
            model_name="instrumento",
            name="maximo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Máximo",
            ),
        ),
        migrations.AlterField(
            model_name="instrumento",
            name="minimo",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Mínimo/Absoluto"
            ),
        ),
        migrations.AlterField(
            model_name="instrumento",
            name="procedimento_relacionado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="procedimentos.procedimento",
            ),
        ),
        migrations.DeleteModel(
            name="ProcedimentoRelacionado",
        ),
        migrations.DeleteModel(
            name="Status",
        ),
        migrations.AddField(
            model_name="unidade",
            name="instrumento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unidades",
                to="instrumentos.instrumento",
            ),
        ),
    ]
