# Generated by Django 4.2 on 2024-03-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0002_unidade_remove_instrumento_unidade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tipoinstrumento",
            name="frequencia",
        ),
        migrations.AddField(
            model_name="instrumentodocliente",
            name="frequencia",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                null=True,
                verbose_name="Frequencia de calibração (em mês)",
            ),
        ),
    ]
