# Generated by Django 4.2 on 2024-04-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0003_remove_tipoinstrumento_frequencia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipoinstrumento",
            name="resolucao",
            field=models.DecimalField(
                blank=True,
                decimal_places=25,
                default=0.0,
                max_digits=60,
                null=True,
                verbose_name="Resolução",
            ),
        ),
    ]
