# Generated by Django 4.2 on 2024-04-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0004_alter_tipoinstrumento_resolucao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumento",
            name="preco_calibracao_no_laboratorio",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Preço calibração no laboratório",
            ),
        ),
    ]
