# Generated by Django 4.2 on 2024-04-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0005_alter_instrumento_preco_calibracao_no_laboratorio"),
    ]

    operations = [
        migrations.AddField(
            model_name="calibracao",
            name="confirmacao_cliente",
            field=models.BooleanField(
                default=False, verbose_name="Confirmação cliente"
            ),
        ),
    ]
