# Generated by Django 4.2 on 2024-04-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0006_calibracao_confirmacao_cliente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calibracao",
            name="confirmacao_cliente",
        ),
        migrations.AddField(
            model_name="calibracao",
            name="analise_critica",
            field=models.CharField(
                choices=[
                    ("A", "Aprovado"),
                    ("X", "Reprovado"),
                    ("R", "Aprovado com restrição"),
                    ("P", "Pendente"),
                ],
                default="P",
                max_length=1,
                verbose_name="Análise Crítica Cliente",
            ),
        ),
        migrations.AddField(
            model_name="calibracao",
            name="restricao_analise_critica",
            field=models.TextField(
                blank=True, null=True, verbose_name="Restrição análise crítica"
            ),
        ),
    ]
