# Generated by Django 4.2 on 2024-04-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0007_remove_calibracao_confirmacao_cliente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumentodocliente",
            name="data_utilizacao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data do início da utilização"
            ),
        ),
    ]
