# Generated by Django 4.2 on 2024-05-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0008_instrumentodocliente_data_utilizacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibracao",
            name="criterio_de_aceitacao",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Critério de aceitação",
            ),
        ),
        migrations.AlterField(
            model_name="calibracao",
            name="data",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da calibração"
            ),
        ),
        migrations.AlterField(
            model_name="calibracao",
            name="incerteza",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="calibracao",
            name="local",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="Local da calibração",
            ),
        ),
        migrations.AlterField(
            model_name="calibracao",
            name="maior_erro",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="calibracao",
            name="numero_do_certificado",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="Número do certificado",
            ),
        ),
        migrations.AlterField(
            model_name="calibracao",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("A", "Aprovado"), ("R", "Reprovado")],
                help_text="Aprovação é definida por: |Maior erro| + |Incerteza| < Critério de aceitação",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="instrumento",
            name="minimo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Mínimo/Absoluto",
            ),
        ),
        migrations.AlterField(
            model_name="tipoinstrumento",
            name="modelo",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="tipoinstrumento",
            name="resolucao",
            field=models.DecimalField(
                blank=True,
                decimal_places=25,
                max_digits=60,
                null=True,
                verbose_name="Resolução",
            ),
        ),
        migrations.AlterField(
            model_name="unidade",
            name="unidade",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
