# Generated by Django 4.2 on 2024-05-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0009_alter_calibracao_criterio_de_aceitacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumentodocliente",
            name="preco_alternativo_calibracao",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Preço alternativo calibração",
            ),
        ),
    ]
