# Generated by Django 4.2 on 2024-06-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0010_instrumentodocliente_preco_alternativo_calibracao"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumentodocliente",
            name="dias_uteis",
            field=models.IntegerField(
                blank=True, help_text="Em dias", null=True, verbose_name="Dias úteis"
            ),
        ),
        migrations.AddField(
            model_name="instrumentodocliente",
            name="local",
            field=models.CharField(
                choices=[
                    ("P", "Instalação permanente"),
                    ("C", "Instalação cliente"),
                    ("T", "Terceirizada"),
                ],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="instrumentodocliente",
            name="prazo_de_entrega",
            field=models.DateField(blank=True, null=True),
        ),
    ]
