# Generated by Django 4.2 on 2024-08-15 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0011_instrumentodocliente_dias_uteis_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PontoDeCalibracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                (
                    "instrumento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pontos_de_calibracao",
                        to="instrumentos.instrumentodocliente",
                    ),
                ),
            ],
        ),
    ]
