# Generated by Django 4.2 on 2024-08-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0012_pontodecalibracao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumentodocliente",
            name="frequencia",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Frequencia de calibração (em mês)"
            ),
        ),
    ]
