# Generated by Django 4.2 on 2024-09-04 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0013_alter_instrumentodocliente_frequencia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instrumentodocliente",
            name="prazo_de_entrega",
        ),
    ]
