# Generated by Django 4.2 on 2024-09-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0014_remove_instrumentodocliente_prazo_de_entrega"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibracao",
            name="criterio_de_aceitacao",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Critério de aceitação"
            ),
        ),
        migrations.AlterField(
            model_name="capacidademedicao",
            name="valor",
            field=models.FloatField(),
        ),
    ]
