# Generated by Django 4.2 on 2024-09-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0015_alter_calibracao_criterio_de_aceitacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumentodocliente",
            name="data_expiracao_calibracao",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Data de expiração da última calibração",
            ),
        ),
        migrations.AddField(
            model_name="instrumentodocliente",
            name="expirado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="instrumentodocliente",
            name="frequencia",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Frequencia de calibração (em dias)"
            ),
        ),
    ]
