# Generated by Django 4.2 on 2024-09-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "instrumentos",
            "0016_instrumentodocliente_data_expiracao_calibracao_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumento",
            name="unidade",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.DeleteModel(
            name="Unidade",
        ),
    ]
