# Generated by Django 4.2 on 2024-10-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0017_instrumento_unidade_delete_unidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumentodocliente",
            name="frequencia",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Frequencia de calibração (em anos)"
            ),
        ),
    ]
