# Generated by Django 4.2 on 2024-10-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0018_alter_instrumentodocliente_frequencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibracao",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("A", "Aprovado"), ("R", "Reprovado")],
                help_text="Aprovação é definida por: |Maior erro| + |Incerteza| <= Critério de aceitação",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="instrumentodocliente",
            name="frequencia",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Frequencia de calibração (em meses)",
            ),
        ),
        migrations.AlterField(
            model_name="tipoinstrumento",
            name="resolucao",
            field=models.FloatField(blank=True, null=True, verbose_name="Resolução"),
        ),
    ]
