# Generated by Django 4.2 on 2024-10-14 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0019_alter_calibracao_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calibracao",
            name="certificado",
        ),
        migrations.RemoveField(
            model_name="calibracao",
            name="numero_do_certificado",
        ),
        migrations.CreateModel(
            name="Certificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Número do certificado",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(blank=True, null=True, upload_to="certificados/"),
                ),
                (
                    "calibracao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados",
                        to="instrumentos.calibracao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Anexo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anexo",
                    models.FileField(
                        blank=True, null=True, upload_to="certificados/anexos/"
                    ),
                ),
                (
                    "certificado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="instrumentos.certificado",
                    ),
                ),
            ],
        ),
    ]
