# Generated by Django 4.2 on 2024-11-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0020_remove_calibracao_certificado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capacidademedicao",
            name="unidade",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
