# Generated by Django 4.2 on 2024-12-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0021_alter_capacidademedicao_unidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibracao",
            name="criterio_de_aceitacao",
            field=models.DecimalField(
                blank=True,
                decimal_places=25,
                max_digits=50,
                null=True,
                verbose_name="Critério de aceitação",
            ),
        ),
        migrations.AlterField(
            model_name="calibracao",
            name="incerteza",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="calibracao",
            name="maior_erro",
            field=models.DecimalField(
                blank=True,
                decimal_places=25,
                max_digits=50,
                null=True,
                verbose_name="Maior erro",
            ),
        ),
    ]
