# Generated by Django 4.2 on 2025-04-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0022_alter_calibracao_criterio_de_aceitacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumentodocliente",
            name="ultima_notificacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
