# Generated by Django 4.2 on 2025-04-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0023_instrumentodocliente_ultima_notificacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumentodocliente",
            name="data_expiracao_calibracao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de expiração calibração"
            ),
        ),
    ]
