# Generated by Django 4.2 on 2025-06-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0024_alter_instrumentodocliente_data_expiracao_calibracao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumentodocliente",
            name="tag",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
