# Generated by Django 4.2 on 2025-06-24 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0003_cliente_instrumentos_cadastrados_and_more"),
        ("instrumentos", "0025_alter_instrumentodocliente_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setores",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "setor_pai",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsetores",
                        to="instrumentos.setor",
                        verbose_name="Setor pai",
                    ),
                ),
            ],
            options={
                "verbose_name": "Setor",
                "verbose_name_plural": "Setores",
            },
        ),
        migrations.AddField(
            model_name="instrumentodocliente",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instrumentos",
                to="instrumentos.setor",
                verbose_name="Setor",
            ),
        ),
    ]
