# Generated by Django 4.2 on 2025-06-24 22:10

from django.db import migrations



def criar_setores_padrao(apps, schema_editor):
    Setor = apps.get_model('instrumentos', 'Setor')
    InstrumentoDoCliente = apps.get_model('instrumentos', 'InstrumentoDoCliente')
    Cliente = apps.get_model('clientes', 'Cliente')

    for cliente in Cliente.objects.all():
        setor_padrao, created = Setor.objects.get_or_create(
            nome='Padrão',
            setor_pai=None,
            cliente=cliente
        )

        InstrumentoDoCliente.objects.filter(setor__isnull=True, cliente=cliente).update(setor=setor_padrao)


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0026_setor_instrumentodocliente_setor"),
        ("clientes", "0003_cliente_instrumentos_cadastrados_and_more"), 
    ]

    operations = [
        migrations.RunPython(criar_setores_padrao),
    ]

