# Generated by Django 4.2 on 2025-06-27 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0027_criar_setores_padrao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumentodocliente",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instrumentos",
                to="instrumentos.setor",
                verbose_name="Setor",
            ),
        ),
    ]
