# Generated by Django 4.2 on 2025-06-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0028_alter_instrumentodocliente_setor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calibracao",
            name="criterio_de_aceitacao",
        ),
        migrations.RemoveField(
            model_name="calibracao",
            name="referencia_do_criterio",
        ),
        migrations.AddField(
            model_name="instrumento",
            name="tipo_sinal",
            field=models.CharField(
                choices=[("A", "Analógico"), ("D", "Digital")],
                default="A",
                max_length=1,
                verbose_name="Tipo de sinal",
            ),
        ),
        migrations.AddField(
            model_name="instrumentodocliente",
            name="classe",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Classe"
            ),
        ),
        migrations.AddField(
            model_name="instrumentodocliente",
            name="criterio_de_aceitacao",
            field=models.DecimalField(
                blank=True,
                decimal_places=25,
                max_digits=50,
                null=True,
                verbose_name="Critério de aceitação",
            ),
        ),
        migrations.AddField(
            model_name="instrumentodocliente",
            name="referencia_do_criterio",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Referência do critério de aceitação",
            ),
        ),
        migrations.AlterField(
            model_name="instrumento",
            name="tipo_de_servico",
            field=models.CharField(
                choices=[
                    ("A", "Acreditado"),
                    ("NA", "Não acreditado"),
                    ("I", "Interno"),
                ],
                default="A",
                max_length=2,
                verbose_name="Tipo de serviço",
            ),
        ),
    ]
