# Generated by Django 4.2 on 2025-07-01 18:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0029_remove_calibracao_criterio_de_aceitacao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Frequencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveSmallIntegerField(
                        help_text="Valor entre 0 e 100",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        choices=[("dia", "dia"), ("mes", "mes"), ("ano", "ano")],
                        help_text="Escolha um período",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Normativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="instrumentodocliente",
            name="frequencia",
        ),
        migrations.AddField(
            model_name="instrumentodocliente",
            name="preco_ultima_calibracao",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Preço ultima calibração",
            ),
        ),
        migrations.AddField(
            model_name="instrumentodocliente",
            name="unidade",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="instrumentodocliente",
            name="frequencia_calibracao",
            field=models.ForeignKey(
                blank=True,
                help_text="Frequência de calibração do instrumento",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instrumentos_calibracao",
                to="instrumentos.frequencia",
            ),
        ),
        migrations.AddField(
            model_name="instrumentodocliente",
            name="frequencia_checagem",
            field=models.ForeignKey(
                blank=True,
                help_text="Frequência de checagem do instrumento",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instrumentos_checagem",
                to="instrumentos.frequencia",
            ),
        ),
        migrations.AddField(
            model_name="instrumentodocliente",
            name="normativos",
            field=models.ManyToManyField(blank=True, to="instrumentos.normativo"),
        ),
    ]
