# Generated by Django 4.2 on 2025-07-01 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0030_frequencia_normativo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instrumentodocliente",
            name="data_proxima_checagem",
        ),
    ]
