# Generated by Django 4.2 on 2025-07-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0031_remove_instrumentodocliente_data_proxima_checagem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instrumentodocliente",
            name="observacoes",
        ),
        migrations.AddField(
            model_name="instrumentodocliente",
            name="observacao_fornecedor",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observações fornecedor"
            ),
        ),
        migrations.AddField(
            model_name="instrumentodocliente",
            name="observacao_status",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observações status"
            ),
        ),
    ]
