# Generated by Django 4.2 on 2025-07-02 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0003_cliente_instrumentos_cadastrados_and_more"),
        ("instrumentos", "0032_remove_instrumentodocliente_observacoes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="normativo",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="normativos",
                to="clientes.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="normativo",
            name="nome",
            field=models.CharField(max_length=255),
        ),
    ]
