# Generated by Django 4.2 on 2025-07-02 16:49

from django.db import migrations


NORMAS_PADRAO = [
    "ISO 9001",
    "IATF 16949",
    "ISO 14001",
    "ISO 45001",
    "ABNT ISO IEC 17025",
]

def add_normas_padroes(apps, schema_editor):
    Cliente = apps.get_model("clientes", "Cliente")
    Normativo = apps.get_model("instrumentos", "Normativo")

    for cliente in Cliente.objects.all():
        normas_existentes = set(Normativo.objects.filter(cliente=cliente).values_list('nome', flat=True))
        for nome in NORMAS_PADRAO:
            if nome not in normas_existentes:
                Normativo.objects.create(nome=nome, cliente=cliente)

def remove_normas_padroes(apps, schema_editor):
    Normativo = apps.get_model("instrumentos", "Normativo")
    Normativo.objects.filter(nome__in=NORMAS_PADRAO).delete()



class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0033_normativo_cliente_alter_normativo_nome"),
    ]

    operations = [
        migrations.RunPython(add_normas_padroes, reverse_code=remove_normas_padroes),
    ]
