# Generated by Django 4.2 on 2025-07-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0034_add_normas_padrao_existentes"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumentodocliente",
            name="observacao_criterio_aceitacao",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observações critério de aceitação"
            ),
        ),
    ]
