# Generated by Django 4.2 on 2025-07-07 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0035_instrumentodocliente_observacao_criterio_aceitacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="calibracao",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calibracoes",
                to="instrumentos.setor",
                verbose_name="Setor",
            ),
        ),
    ]
