# Generated by Django 4.2 on 2025-07-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0036_calibracao_setor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumentodocliente",
            name="posicao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("U", "Em uso"),
                    ("E", "Em estoque"),
                    ("I", "Inativo"),
                    ("F", "Fora de uso"),
                ],
                max_length=1,
                null=True,
                verbose_name="Posição do instrumento",
            ),
        ),
    ]
