# Generated by Django 4.2 on 2025-08-04 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0003_cliente_instrumentos_cadastrados_and_more"),
        ("instrumentos", "0037_alter_instrumentodocliente_posicao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instrumentodocliente",
            name="data_expiracao_calibracao",
        ),
        migrations.RemoveField(
            model_name="instrumentodocliente",
            name="laboratorio",
        ),
        migrations.RemoveField(
            model_name="instrumentodocliente",
            name="observacao_fornecedor",
        ),
        migrations.RemoveField(
            model_name="instrumentodocliente",
            name="preco_ultima_calibracao",
        ),
    ]
