# Generated by Django 4.2 on 2025-08-04 13:10

from django.db import migrations, models
import django


class Migration(migrations.Migration):
    dependencies = [
        (
            "instrumentos",
            "0038_remove_instrumentodocliente_data_expiracao_calibracao_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="calibracao",
            name="laboratorio",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="calibracao",
            name="observacao_fornecedor",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observações fornecedor"
            ),
        ),
        migrations.AddField(
            model_name="calibracao",
            name="preco",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Preço ultima calibração",
            ),
        ),
         migrations.AddField(
            model_name="instrumentodocliente",
            name="data_proxima_checagem",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da próxima checagem"
            ),
        ), 
        migrations.AddField(
            model_name="instrumentodocliente",
            name="data_ultima_checagem",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da última checagem"
            ),
        ),
        migrations.AlterField(
            model_name="calibracao",
            name="incerteza",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="calibracao",
            name="maior_erro",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=10,
                null=True,
                verbose_name="Maior erro",
            ),
        ),
        migrations.AlterField(
            model_name="instrumentodocliente",
            name="criterio_de_aceitacao",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=10,
                null=True,
                verbose_name="Critério de aceitação",
            ),
        ),
        migrations.CreateModel(
            name="HistoricoPosicaoInstrumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nova_posicao",
                    models.CharField(
                        choices=[
                            ("U", "Em uso"),
                            ("E", "Em estoque"),
                            ("I", "Inativo"),
                            ("F", "Fora de uso"),
                        ],
                        max_length=1,
                    ),
                ),
                ("data_alteracao", models.DateTimeField(auto_now_add=True)),
                (
                    "instrumento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_posicoes",
                        to="instrumentos.instrumentodocliente",
                    ),
                ),
                (
                    "usuario_alteracao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_alteracao"],
            },
        ),
    ]
