# Generated by Django 4.2 on 2025-08-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0039_auto_20250804_1010"),
    ]

    operations = [
        migrations.AddField(
            model_name="calibracao",
            name="checagem",
            field=models.BooleanField(default=False),
        ),
    ]
