# Generated by Django 4.2 on 2025-08-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0040_calibracao_checagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicoposicaoinstrumento",
            name="antiga_posicao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("U", "Em uso"),
                    ("E", "Em estoque"),
                    ("I", "Inativo"),
                    ("F", "Fora de uso"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
