# Generated by Django 4.2 on 2025-08-07 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0003_cliente_instrumentos_cadastrados_and_more"),
        ("instrumentos", "0041_historicoposicaoinstrumento_antiga_posicao"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricoPosicaoInstrumento",
            new_name="MovimentacaoInstrumento",
        ),
    ]
