# Generated by Django 4.2 on 2025-08-08 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "instrumentos",
            "0042_rename_historicoposicaoinstrumento_movimentacaoinstrumento",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calibracao",
            name="local",
        ),
        migrations.RemoveField(
            model_name="instrumentodocliente",
            name="local",
        ),
    ]
