# Generated by Django 4.2 on 2025-08-15 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0044_calibracao_local"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instrumentodocliente",
            name="criterio_de_aceitacao",
        ),
        migrations.RemoveField(
            model_name="instrumentodocliente",
            name="observacao_criterio_aceitacao",
        ),
        migrations.RemoveField(
            model_name="instrumentodocliente",
            name="observacao_status",
        ),
        migrations.RemoveField(
            model_name="instrumentodocliente",
            name="referencia_do_criterio",
        ),
        migrations.AddField(
            model_name="instrumentodocliente",
            name="observacao",
            field=models.TextField(blank=True, null=True, verbose_name="Observação"),
        ),
        migrations.AlterField(
            model_name="instrumentodocliente",
            name="posicao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("U", "Em uso"),
                    ("E", "Em estoque"),
                    ("I", "Inativo"),
                    ("F", "Fora de uso"),
                    ("C", "Em calibração"),
                ],
                max_length=1,
                null=True,
                verbose_name="Posição do instrumento",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoinstrumento",
            name="antiga_posicao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("U", "Em uso"),
                    ("E", "Em estoque"),
                    ("I", "Inativo"),
                    ("F", "Fora de uso"),
                    ("C", "Em calibração"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaoinstrumento",
            name="nova_posicao",
            field=models.CharField(
                choices=[
                    ("U", "Em uso"),
                    ("E", "Em estoque"),
                    ("I", "Inativo"),
                    ("F", "Fora de uso"),
                    ("C", "Em calibração"),
                ],
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="CriterioAceitacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100, verbose_name="Tipo")),
                (
                    "criterio_de_aceitacao",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=10,
                        null=True,
                        verbose_name="Critério de aceitação",
                    ),
                ),
                (
                    "referencia_do_criterio",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Referência do critério de aceitação",
                    ),
                ),
                (
                    "observacao_criterio_aceitacao",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Observações critério de aceitação",
                    ),
                ),
                (
                    "instrumento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterios_aceitacao",
                        to="instrumentos.instrumentodocliente",
                    ),
                ),
            ],
        ),
    ]
