# Generated by Django 4.2 on 2025-08-15 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "instrumentos",
            "0045_remove_instrumentodocliente_criterio_de_aceitacao_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calibracao",
            name="incerteza",
        ),
        migrations.RemoveField(
            model_name="calibracao",
            name="maior_erro",
        ),
        migrations.RemoveField(
            model_name="calibracao",
            name="status",
        ),
        migrations.CreateModel(
            name="ResultadoCalibracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("A", "Aprovado"), ("R", "Reprovado")],
                        help_text="Aprovação é definida por: |Maior erro| + |Incerteza| <= Critério de aceitação",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "maior_erro",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=10,
                        null=True,
                        verbose_name="Maior erro",
                    ),
                ),
                (
                    "incerteza",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "calibracao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="instrumentos.calibracao",
                    ),
                ),
            ],
        ),
    ]
