# Generated by Django 4.2 on 2025-08-18 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0003_cliente_instrumentos_cadastrados_and_more"),
        ("instrumentos", "0046_remove_calibracao_incerteza_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instrumentodocliente",
            name="unidade",
        ),
        migrations.AddField(
            model_name="criterioaceitacao",
            name="unidade",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.CreateModel(
            name="MovimentacaoSetorInstrumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_alteracao", models.DateTimeField(auto_now_add=True)),
                ("novo_setor", models.CharField(max_length=255)),
                ("antigo_setor", models.CharField(max_length=255)),
                (
                    "instrumento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_setores",
                        to="instrumentos.instrumentodocliente",
                    ),
                ),
                (
                    "usuario_alteracao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_alteracao"],
            },
        ),
    ]
