# Generated by Django 4.2 on 2025-08-20 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0047_remove_instrumentodocliente_unidade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultadocalibracao",
            name="criterio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultados",
                to="instrumentos.criterioaceitacao",
            ),
        ),
    ]
