# Generated by Django 4.2 on 2025-08-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0048_resultadocalibracao_criterio"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumentodocliente",
            name="data_criacao",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
