# Generated by Django 4.2 on 2025-08-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0049_instrumentodocliente_data_criacao"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="instrumentodocliente",
            constraint=models.UniqueConstraint(
                fields=("cliente", "tag"), name="unique_tag_por_cliente"
            ),
        ),
    ]
