# Generated by Django 4.2 on 2025-09-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0050_instrumentodocliente_unique_tag_por_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumentodocliente",
            name="criterio_frequencia",
            field=models.CharField(
                blank=True,
                choices=[("C", "Tempo de calendário"), ("S", "Tempo de serviço")],
                max_length=1,
                null=True,
                verbose_name="Critério de frequência",
            ),
        ),
    ]
