# Generated by Django 4.2 on 2025-09-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0051_instrumentodocliente_criterio_frequencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumento",
            name="tipo_de_servico",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "Acreditado"),
                    ("NA", "Não acreditado"),
                    ("I", "Interno"),
                ],
                max_length=2,
                null=True,
                verbose_name="Tipo de serviço",
            ),
        ),
        migrations.AlterField(
            model_name="instrumento",
            name="tipo_sinal",
            field=models.CharField(
                blank=True,
                choices=[("A", "Analógico"), ("D", "Digital")],
                max_length=1,
                null=True,
                verbose_name="Tipo de sinal",
            ),
        ),
    ]
