# Generated by Django 4.2 on 2025-09-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0052_alter_instrumento_tipo_de_servico_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibracao",
            name="checagem",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="calibracao",
            name="local",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P", "Instalação permanente"),
                    ("C", "Instalação cliente"),
                    ("T", "Terceirizada"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
