# Generated by Django 4.2 on 2025-09-25 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("instrumentos", "0053_alter_calibracao_checagem_alter_calibracao_local"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimentacaoinstrumento",
            name="usuario_alteracao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaosetorinstrumento",
            name="usuario_alteracao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
