# Generated by Django 4.2 on 2025-10-25 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0010_cliente_criterio_frequencia_padrao"),
        (
            "instrumentos",
            "0054_alter_movimentacaoinstrumento_usuario_alteracao_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="InstrumentoBaseCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Se o cliente tem acesso a este instrumento",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrumentos_disponiveis",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "instrumento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientes_acesso",
                        to="instrumentos.instrumento",
                        verbose_name="Instrumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrumento Base do Cliente",
                "verbose_name_plural": "Instrumentos Base dos Clientes",
                "unique_together": {("instrumento", "cliente")},
            },
        ),
    ]
