# Generated by Django 4.2 on 2025-11-17 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0055_instrumentobasecliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frequencia",
            name="quantidade",
            field=models.PositiveSmallIntegerField(
                help_text="Valor entre 0 e 366",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(366),
                ],
            ),
        ),
    ]
