# Generated by Django 4.2 on 2025-11-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0056_alter_frequencia_quantidade"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="instrumentodocliente",
            index=models.Index(fields=["tag"], name="instrumento_tag_1cfa8c_idx"),
        ),
        migrations.AddIndex(
            model_name="instrumentodocliente",
            index=models.Index(
                fields=["cliente", "tag"], name="instrumento_cliente_9394b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tipoinstrumento",
            index=models.Index(
                fields=["descricao"], name="instrumento_descric_c2b61c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tipoinstrumento",
            index=models.Index(fields=["modelo"], name="instrumento_modelo_b297a7_idx"),
        ),
        migrations.AddIndex(
            model_name="tipoinstrumento",
            index=models.Index(
                fields=["fabricante"], name="instrumento_fabrica_dc1856_idx"
            ),
        ),
    ]
