# Generated by Django 4.2 on 2025-11-25 22:21

from django.db import migrations, models, connection


def add_indexes_if_not_exists(apps, schema_editor):
    """Add indexes only if they don't already exist"""
    with connection.cursor() as cursor:
        indexes_to_add = [
            ("instrumentos_instrumentodocliente", "tag", "instrumento_tag_1cfa8c_idx"),
            ("instrumentos_instrumentodocliente", "cliente,tag", "instrumento_cliente_9394b8_idx"),
        ]
        
        for table_name, fields, index_name in indexes_to_add:
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = %s 
                AND index_name = %s
            """, [table_name, index_name])
            
            if cursor.fetchone()[0] == 0:
                if ',' in fields:
                    field_list = fields.split(',')
                    cursor.execute(f"""
                        CREATE INDEX {index_name} 
                        ON {table_name} ({','.join(field_list)})
                    """)
                else:
                    cursor.execute(f"""
                        CREATE INDEX {index_name} 
                        ON {table_name} ({fields})
                    """)
        
        tipo_indexes = [
            ("instrumentos_tipoinstrumento", "descricao", "instrumento_descric_c2b61c_idx"),
            ("instrumentos_tipoinstrumento", "modelo", "instrumento_modelo_b297a7_idx"),
            ("instrumentos_tipoinstrumento", "fabricante", "instrumento_fabrica_dc1856_idx"),
        ]
        
        for table_name, field, index_name in tipo_indexes:
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = %s 
                AND index_name = %s
            """, [table_name, index_name])
            
            if cursor.fetchone()[0] == 0:
                cursor.execute(f"""
                    CREATE INDEX {index_name} 
                    ON {table_name} ({field})
                """)


def remove_indexes(apps, schema_editor):
    """Remove indexes if they exist"""
    with connection.cursor() as cursor:
        indexes_to_remove = [
            ("instrumentos_instrumentodocliente", "instrumento_tag_1cfa8c_idx"),
            ("instrumentos_instrumentodocliente", "instrumento_cliente_9394b8_idx"),
            ("instrumentos_tipoinstrumento", "instrumento_descric_c2b61c_idx"),
            ("instrumentos_tipoinstrumento", "instrumento_modelo_b297a7_idx"),
            ("instrumentos_tipoinstrumento", "instrumento_fabrica_dc1856_idx"),
        ]
        
        for table_name, index_name in indexes_to_remove:
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = %s 
                AND index_name = %s
            """, [table_name, index_name])
            
            if cursor.fetchone()[0] > 0:
                cursor.execute(f"DROP INDEX {index_name} ON {table_name}")


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0056_alter_frequencia_quantidade"),
    ]

    operations = [
        migrations.RunPython(add_indexes_if_not_exists, remove_indexes),
    ]
