# Generated by Django 4.2 on 2025-12-08 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "instrumentos",
            "0057_instrumentodocliente_instrumento_tag_1cfa8c_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumentodocliente",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instrumentos",
                to="instrumentos.setor",
                verbose_name="Setor",
            ),
        ),
    ]
