# Generated by Django 4.2 on 2026-01-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0058_alter_instrumentodocliente_setor"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumentodocliente",
            name="numero_certificado",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Número do certificado",
            ),
        ),
    ]
