# Generated by Django 4.2 on 2026-03-25 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0059_instrumentodocliente_numero_certificado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibracao",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calibracoes",
                to="instrumentos.setor",
                verbose_name="Setor",
            ),
        ),
    ]
