# Generated by Django 4.2 on 2026-04-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0060_alter_calibracao_setor"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumentodocliente",
            name="tipo_de_servico",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "Acreditado"),
                    ("NA", "Não acreditado"),
                    ("I", "Interno"),
                ],
                max_length=2,
                null=True,
                verbose_name="Tipo de serviço",
            ),
        ),
    ]
