# Generated by Django 4.2 on 2026-05-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("instrumentos", "0061_instrumentodocliente_tipo_de_servico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultadocalibracao",
            name="criterio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resultados",
                to="instrumentos.criterioaceitacao",
            ),
        ),
    ]
