name: Deploy Landing via FTP

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'bef-landing-page/**'
      - '.github/workflows/deploy-landingpage.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 📄 Making .env
        run: |
          cd bef-landing-page
          echo "${{ secrets.NEXT_PUBLIC_API_URL }}" > .env

      - name: Build Next.js
        run: |
          cd bef-landing-page
          npm install
          npm run export
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./bef-landing-page/out/
          server-dir: /home/kometro/
          log-level: verbose
          dry-run: true
